"""行程分享 API — 生成分享链接 + 通过 token 查看行程"""

import secrets
from fastapi import APIRouter, Depends
from pydantic import BaseModel
from sqlalchemy.orm import Session
import json

from database.models import get_db, SavedTrip
from utils.logger import logger

router = APIRouter()

# 内存 token 映射（简单实现，生产环境可用 Redis）
_share_tokens: dict = {}  # token -> trip_id


class ShareResponse(BaseModel):
    url: str
    token: str


@router.post("/api/share/{trip_id}", response_model=ShareResponse)
async def create_share_link(trip_id: int, db: Session = Depends(get_db)):
    """为行程生成分享链接"""
    trip = db.query(SavedTrip).filter(SavedTrip.id == trip_id).first()
    if not trip:
        return {"url": "", "token": ""}

    token = secrets.token_urlsafe(8)
    _share_tokens[token] = trip_id
    logger.info(f"创建分享链接: trip_id={trip_id}, token={token}")
    return {"url": f"/detail/{token}", "token": token}


@router.get("/api/share/{token}")
async def get_shared_trip(token: str, db: Session = Depends(get_db)):
    """通过分享 token 查看行程"""
    trip_id = _share_tokens.get(token)
    if not trip_id:
        return {"error": "分享链接无效或已过期"}

    trip = db.query(SavedTrip).filter(SavedTrip.id == trip_id).first()
    if not trip:
        return {"error": "行程不存在"}

    return {
        "id": trip.id,
        "destination": trip.destination,
        "days": trip.days,
        "budget": trip.budget,
        "preferences": trip.preferences.split(",") if trip.preferences else [],
        "itinerary": json.loads(trip.itinerary_json),
        "verification": json.loads(trip.verification_json) if trip.verification_json else None,
        "created_at": trip.created_at.strftime("%Y-%m-%d %H:%M") if trip.created_at else "",
    }


@router.get("/api/export/{trip_id}")
async def export_trip(trip_id: int, format: str = "json", db: Session = Depends(get_db)):
    """导出行程为 JSON 或 Markdown"""
    trip = db.query(SavedTrip).filter(SavedTrip.id == trip_id).first()
    if not trip:
        return {"error": "行程不存在"}

    itinerary_data = json.loads(trip.itinerary_json)

    if format == "markdown":
        lines = [
            f"# {trip.destination} {trip.days}天行程",
            "",
            f"> {itinerary_data.get('summary', '')}",
            "",
            f"- **预算**: ¥{trip.budget}",
            f"- **总花费**: ¥{trip.total_cost}",
            f"- **偏好**: {trip.preferences}",
            "",
        ]
        for day in itinerary_data.get("itinerary", []):
            lines.append(f"## Day {day['day']} — ¥{day.get('day_cost', 0)}")
            lines.append(f"**交通**: {day.get('transport', '')}")
            lines.append("")
            for item in day.get("items", []):
                cost_str = "免费" if item.get("cost", 0) == 0 else f"¥{item['cost']}"
                lines.append(f"- `{item['time']}` **{item['spot']}** ({item['category']}) — {item['duration']} | {cost_str}")
                if item.get("note"):
                    lines.append(f"  - {item['note']}")
            lines.append("")
        lines.append("---")
        lines.append("*Generated by TripCraft*")
        return {"format": "markdown", "content": "\n".join(lines)}

    # JSON 格式
    return {
        "format": "json",
        "content": json.dumps(itinerary_data, ensure_ascii=False, indent=2),
    }